name: fastapi_uidtoken
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - passlib
  - loguru
  - fastapi
  - starlette
  - uvicorn
  - pyjwt
  - python-multipart
  - alembic         # for dataset, so conda installs deps, not pip
  - sqlalchemy      # for dataset
  - pip:
    - dataset
    - uvicorn-loguru-integration

